CC=gcc
CFLAGS=-Wall
SensorThread: SensorThread.c O2Sensor.c GasDisplay.c GasDataQueue.c GasData.c GasController.c

clean:
	rm -f main SensorThread.o O2Sensor.o GasDisplay.o GasDataQueue.o GasData.o GasController.o
