CC=gcc                                                                                                                                                                                                              
CFLAGS=-Wall                                                                                                                                                                                                        
layer: layer.o                                                                                                                                                                                                      
                                                                                                                                                                                                                    
clean:                                                                                                                                                                                                              
        rm -f layer layer.o
