/***
    LeetCode : Find the Difference
    https://leetcode.com/problems/find-the-difference/
    https://leetcode.com/explore/featured/card/september-leetcoding-challenge/557/week-4-september-22nd-september-28th/3471/
    Given two strings s and t which consist of only lowercase letters.

    String t is generated by random shuffling string s and then add one more letter at a random position.
    Find the letter that was added in t.
    Example:
    Input:
    s = "abcd"
    t = "abcde"
    Output:
    e
    Explanation:
    'e' is the letter that was added.
    Logic : https://www.youtube.com/watch?v=sRwElQ_TOr8
    Use XOR 1 ^ 1 = 0 & 0 ^ 0 = 0 & rest all are 1, so easy to cancel same element.

    Date: Fri Sep 25 11:50:40 2020 -0700
    Place: San Diego

*/
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <limits.h>
#include <string.h>  /* malloc */
#include <stdbool.h>
#include <math.h>
#include <assert.h>
#include <stdint.h> /* uint32_t */
#include <unistd.h> /* sleep */

/*----------------------------------- Micro --------------------------------------*/
#define debug(str,args...) printf("[%s] L=%d :"str"\n", __func__, __LINE__, ##args)
#define atsizeof(object) (char *)(&object+1) - (char*)(&object)
#define arrsz(x)  (sizeof(x) / sizeof((x)[0]))
#define max(a,b)		\
  ({ __typeof__ (a) _a = (a);	\
    __typeof__ (b) _b = (b);	\
    _a > _b ? _a : _b; })
#define min(a,b)		\
  ({ __typeof__ (a) _a = (a);	\
    __typeof__ (b) _b = (b);	\
    _a < _b ? _a : _b; })
/*----------------------------------- Micro --------------------------------------*/

/* Optimal Solution */
char findTheDifference(char * s, char * t) {
  char ans = 0;
    register int i;
    for (i = 0; s[i] != '\0'; i++) {
        ans ^= s[i];
	debug ("i=%d ans= %d", i, ans);
        ans ^= t[i];
	debug ("i=%d ans= %d", i, ans);
    }
    debug ("i=%d ans= %d", i, ans^t[i]);
    ans ^= t[i];

    return ans;

}

/* Brute force */
char findTheDifference2 (char * s, char * t) {
  int i, flag = 0;
  char isPresent[26] = {0};

  int slen = strlen (s);
  int tlen = strlen (t);
  for (i=0; i<slen; i++)
    ++isPresent[s[i]];

  for (i=0; i<tlen; i++) {
    if (isPresent[t[i]])  {
      debug (" --> %c", t[i]);
    } else
      flag = i;
  }
  debug ("flag = %d", flag);
  return t[flag];
}


int main () {
  char *s = "abcd";
  char *t = "abcde";
  printf ("[%s] output = %c \n", __func__, findTheDifference(s, t));
  debug(" Enter ");
}

/***
    [main] output = e
    [string/find_diff.c] [main()] L=63 : Enter
*/

/**
   => ./a.out
   [findTheDifference] L=55 :i=0 ans= 97
   [findTheDifference] L=57 :i=0 ans= 0
   [findTheDifference] L=55 :i=1 ans= 98
   [findTheDifference] L=57 :i=1 ans= 0
   [findTheDifference] L=55 :i=2 ans= 99
   [findTheDifference] L=57 :i=2 ans= 0
   [findTheDifference] L=55 :i=3 ans= 100
   [findTheDifference] L=57 :i=3 ans= 0
   [findTheDifference] L=59 :i=4 ans= 101
   [main] output = e
   [main] L=91 : Enter
**/
